function renderStage(){save();if(state.stage<0)state.stage=0;if(state.stage>=STAGES.length)state.stage=13;const fn={difficulty:renderDifficulty,teamFormation:renderTeam,problemReveal:renderProblem,solutionDirection:renderDirection,techStack:renderTech,usp:renderUSP,features:renderFeatures,pitchDeck:renderDeck,mentor:renderMentor,businessModel:renderBusiness,pitchPrep:renderPitch,judgeSpin:renderJudgeSpin,judging:renderJudging,results:renderResults}[STAGES[state.stage]];fn();window.scrollTo({top:0,behavior:'smooth'})}
function back(){if(state.stage>0){state.stage--;renderStage()}}
function abortGame(){if(confirm('Give up on this hackathon run? Current progress will be cleared.')){localStorage.removeItem('vasukiHackathonCurrent');goHome()}}
function next(){if(!canNext())return;if(state.stage===1&&!state.timerStarted)startTimer();if(state.stage===2&&!state.timerStarted)startTimer();maybeChaos(()=>{state.stage++;renderStage()})}
function canNext(){switch(state.stage){case 0:return!!state.difficulty;case 1:return state.team.length>=2;case 2:return!!state.problem;case 3:return!!state.direction;case 4:return state.tech.length>=4;case 5:return!!state.usp;case 6:return state.features.length>=6;case 7:return state.deck.length>=6;case 8:return state.mods.includes('NO_MENTOR')||!!state.mentor;case 9:return!!state.business;case 10:return state.pitch.trim().length>=80;case 11:return!!state.judge;case 12:return state.judged;case 13:return false;default:return true}}
function maybeChaos(done){if(![3,4,6,9].includes(state.stage)||state.chaos.length>=3){done();return}const chance=state.mods.includes('CHAOS_MAGNET')?.35:.15;if(Math.random()>chance){done();return}const available=CHAOS.filter((_,i)=>!state.chaos.includes(i));if(!available.length){done();return}const ev=available[Math.floor(Math.random()*available.length)],idx=CHAOS.indexOf(ev);const root=document.getElementById('chaosRoot');root.innerHTML=`<div class="chaosOverlay"><div class="chaos"><div class="chip dark">⚠ CHAOS EVENT</div><h2>${esc(ev.title)}</h2><p>${esc(ev.desc)}</p><div class="chaosChoices">${ev.choices.map((c,i)=>`<button class="chaosChoice" onclick="resolveChaos(${idx},${i})"><b>${esc(c[0])}</b><small style="display:block;color:#888;margin-top:4px">Choose quickly. This changes hidden score and time.</small></button>`).join('')}</div></div></div>`;window.__chaosDone=done}
function resolveChaos(idx,choice){const m=CHAOS[idx].choices[choice][1];['innovation','execution','design','pitch','bonus'].forEach(k=>{if(m[k])state.score[k]=Math.max(0,Math.min(100,(state.score[k]||0)+m[k]))});if(m.time){state.time=Math.max(0,state.time+m.time)}state.chaos.push(idx);document.getElementById('chaosRoot').innerHTML='';save();const cb=window.__chaosDone;window.__chaosDone=null;if(cb)cb()}
function renderDifficulty(){const opts=[['easy','RELAXED BUILD (EASY)',state.mode==='speedrun'?'3-minute countdown // 1.0x score multiplier':'10-minute countdown // 1.0x score multiplier. Perfect for planning and exploring.'],['medium','STANDARD HACK (MEDIUM)',state.mode==='speedrun'?'3-minute countdown // 1.15x score multiplier':'7-minute countdown // 1.15x score multiplier. Classic high-pressure pace.'],['hard','CRUNCH TIME (HARD)',state.mode==='speedrun'?'3-minute countdown // 1.30x score multiplier':'5-minute countdown // 1.30x score multiplier. Quick decisions and maximum intensity.'],['dev','SPEED BUILD (DEV)',state.mode==='speedrun'?'3-minute countdown // 1.0x score multiplier':'60-second countdown // developer test run.']];const body=`<div class="options">${opts.map(o=>`<button class="option ${state.difficulty===o[0]?'active':''}" onclick="chooseDifficulty('${o[0]}')"><strong>${o[1]}</strong><small>${o[2]}</small></button>`).join('')}</div><div style="max-width:650px;margin:18px auto 0"><div class="paneltitle">OPTIONAL HACKATHON RULE MODIFIERS · PICK UP TO 2</div><div class="modifierGrid">${MODS.map(m=>`<button class="modifier ${state.mods.includes(m[0])?'active':''}" onclick="toggleMod('${m[0]}')"><b>${m[1]}</b><small>${m[2]}</small></button>`).join('')}</div></div>`;document.getElementById('app').innerHTML=stageShell('Choose Your Pace','Decide how much time you want. Shorter clocks increase final score multipliers.',body,!state.difficulty)}
function chooseDifficulty(d){state.difficulty=d;state.totalTime=state.mode==='speedrun'?180:{easy:600,medium:420,hard:300,dev:60}[d];state.time=state.totalTime;renderStage()}
function toggleMod(id){if(state.mods.includes(id))state.mods=state.mods.filter(x=>x!==id);else if(state.mods.length<2)state.mods.push(id);else return toast('MAXIMUM 2 MODIFIERS');renderStage()}
function renderTeam(){const body=`<div class="teamgrid">${TEAM.map(t=>`<button class="teamcard ${state.team.includes(t.id)?'active':''}" onclick="toggleTeam('${t.id}')"><div class="avatar">${t.emoji}</div><b>${t.name}</b><small>${t.role}</small><small>${t.desc}</small></button>`).join('')}</div><div class="teamcount">SELECT 2–4 TEAMMATES · ${state.team.length}/4 SELECTED</div>`;document.getElementById('app').innerHTML=stageShell('Assemble Your Team','Choose teammates whose strengths match the project you want to build.',body,state.team.length<2)}
function toggleTeam(id){if(state.team.includes(id))state.team=state.team.filter(x=>x!==id);else if(state.team.length<4)state.team.push(id);renderStage()}
function randomProblem(){let pool=PROBLEMS;if(state.difficulty&&state.difficulty!=='dev'){const map={easy:'beginner',medium:'intermediate',hard:'advanced'};const exact=pool.filter(p=>p.difficulty===map[state.difficulty]);if(exact.length)pool=exact}state.problem=pool[Math.floor(Math.random()*pool.length)].id;renderStage()}
function renderProblem(){const p=PROBLEMS.find(x=>x.id===state.problem);const body=p?`<div class="problem"><div class="cat"><span>${esc(p.category)} // ${esc(p.difficulty)}</span><span>${esc(p.id)}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="constraints">${p.constraints.map(x=>`<div class="constraint"><b>CONSTRAINT</b><br>${esc(x)}</div>`).join('')}${p.bonusObjectives.map(x=>`<div class="constraint"><b>BONUS OBJECTIVE</b><br>${esc(x)}</div>`).join('')}</div><div class="constraint" style="margin-top:8px"><b>JUDGING HINT</b><br>${esc(p.judgingHint)}</div></div><button class="btn shuffle" onclick="randomProblem()">↻ SHUFFLE PROBLEM</button>`:`<div class="problem" style="text-align:center"><h3>RANDOM PROBLEM ENGINE</h3><p>Draw one of 22 curated hackathon problem statements.</p><button class="launch" style="margin-top:14px" onclick="randomProblem()">REVEAL PROBLEM</button></div>`;document.getElementById('app').innerHTML=stageShell('Round 1: Problem Reveal','Your challenge is randomized from the original curated problem database.',body,!state.problem)}
function renderDirection(){const body=`<div class="options">${DIRECTIONS.map(o=>`<button class="option ${state.direction===o.id?'active':''}" onclick="chooseDirection('${o.id}')"><strong>${o.name}</strong><small>${o.desc}</small></button>`).join('')}</div>`;document.getElementById('app').innerHTML=stageShell('Round 2: Define Your Solution','Your format shapes stack fit and how judges evaluate execution and design.',body,!state.direction)}
