let state={};let timerHandle=null;let selectedMode='classic';
function fresh(){return {stage:0,mode:selectedMode,difficulty:null,totalTime:0,time:0,timerStarted:false,mods:[],team:[],problem:null,direction:null,tech:[],usp:null,features:[],deck:[],mentor:null,mentorApplied:false,business:null,pitch:'',judge:null,score:{innovation:20,execution:20,design:20,pitch:20,bonus:0},chaos:[],judged:false,final:null};}
function save(){try{localStorage.setItem('vasukiHackathonCurrent',JSON.stringify(state))}catch(e){}}
function load(){try{const s=JSON.parse(localStorage.getItem('vasukiHackathonCurrent')||'null');if(s&&s.stage>=0&&s.stage<STAGES.length)return s}catch(e){}return null}
function goHome(){clearInterval(timerHandle);timerHandle=null;state=fresh();renderLanding()}
function formatTime(n){n=Math.max(0,Math.floor(n||0));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1700)}
function runs(){try{return JSON.parse(localStorage.getItem('vasukiHackathonRuns')||'[]')}catch(e){return[]}}
function renderLanding(){const rs=runs();document.getElementById('app').innerHTML=`<section class="landing"><div class="kicker">🏆 A DECISION-DRIVEN SIMULATION GAME</div><h1>BUILD. SHIP.<br><span>SURVIVE.</span></h1><p class="desc">Experience a complete hackathon journey from team assembly to final judging. Every decision changes your innovation, execution, design and pitch score.</p><div class="runner"><span class="runnerver">GAME RUNNER V2.4</span><div class="seqtitle"><i class="pulse"></i> THE REAL GAME SEQUENCE</div><div class="sequence"><div><b>01/</b><span>Choose your pace & hackathon rules</span></div><div><b>02/</b><span>Assemble your product team</span></div><div><b>03/</b><span>Receive a randomized problem statement</span></div><div><b>04/</b><span>Build stack, USP, backlog & pitch storyboard</span></div><div><b>05/</b><span>Survive chaos, mentor review & jury judging</span></div></div><div class="modes"><button class="mode ${selectedMode==='classic'?'active':''}" onclick="pickMode('classic')">CLASSIC</button><button class="mode ${selectedMode==='speedrun'?'active':''}" onclick="pickMode('speedrun')">SPEEDRUN</button><button class="mode ${selectedMode==='daily'?'active':''}" onclick="pickMode('daily')">DAILY</button></div><button class="launch" onclick="startGame()">LAUNCH HACKATHON →</button>${load()?'<button class="btn" style="width:100%;margin-top:7px" onclick="resumeGame()">RESUME SAVED RUN</button>':''}</div><div class="statsline"><span>22 Problems</span><span>15 Technologies</span><span>5 Judges</span><span>14 Stages</span></div>${rs.length?`<div class="history"><b>LAST RUN:</b> ${esc(rs[0].grade)} · ${rs[0].score}/100 · ${esc(rs[0].problem)}</div>`:''}<div class="founderline">Founder Edition · <a href="https://vasukinfc.in/" target="_blank" rel="noopener">Vasuki NFC</a> · Hemshankar Agarwal</div></section>`}
function pickMode(m){selectedMode=m;renderLanding()}
function startGame(){state=fresh();state.mode=selectedMode;save();renderStage()}
function resumeGame(){state=load()||fresh();selectedMode=state.mode||'classic';renderStage();if(state.timerStarted&&state.time>0)startTimer()}
function startTimer(){if(timerHandle||!state.totalTime)return;state.timerStarted=true;timerHandle=setInterval(()=>{if(state.stage>=13){clearInterval(timerHandle);timerHandle=null;return}state.time--;if(state.time<=0){state.time=0;clearInterval(timerHandle);timerHandle=null;toast('TIME EXPIRED — FINAL JUDGING');state.stage=11;if(!state.judge)state.judge=JUDGES[Math.floor(Math.random()*JUDGES.length)].id;renderStage()}else{save();const el=document.getElementById('timer');if(el){el.textContent=formatTime(state.time);el.className='timer '+(state.time<31?'danger':state.time<91?'warn':'')}}},1000)}
function stageShell(title,subtitle,body,disableNext=false,nextLabel='NEXT ROUND >'){const i=state.stage;const timer=state.difficulty?`<span id="timer" class="timer ${state.time<31?'danger':state.time<91?'warn':''}">${formatTime(state.time)}</span>`:'';return `<section class="stage"><div class="stageCard"><div class="stageMeta"><div class="left"><span>${i===0?'GETTING STARTED':i===13?'HACKATHON CONCLUDED':`ROUND ${i} OF 11`} // ${STAGE_LABELS[i]}</span>${state.mode?`<span class="chip dark">MODE: ${state.mode}</span>`:''}${state.difficulty?`<span class="chip">PACE: ${state.difficulty}</span>`:''}</div>${timer}</div><h2 class="stageTitle">${title}</h2><p class="subtitle">${subtitle}</p>${body}<div class="navrow"><div><button class="btn" onclick="back()" ${i===13?'disabled':''}>&lt; BACK</button>${i>0&&i<13?'<button class="btn danger" style="margin-left:6px" onclick="abortGame()">GIVE UP</button>':''}</div><div class="dots">${STAGES.map((_,x)=>`<i class="dot ${x<i?'done':x===i?'now':''}"></i>`).join('')}</div><button class="btn primary" onclick="next()" ${disableNext?'disabled':''}>${nextLabel}</button></div></div></section>`}
